# Generated by Django 3.1.4 on 2020-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='address',
            field=models.CharField(max_length=264),
        ),
    ]
