# Generated by Django 3.1.4 on 2020-12-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20201214_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='bloodgroup',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='name',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='name',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
